FIND_PACKAGE(NetCDF REQUIRED)

FIND_PATH(EXODUS_INCLUDE_DIR NAMES exodusII.h)

FIND_LIBRARY(EXODUS_LIBRARIES NAMES exodusii exodusIIv2c)

INCLUDE(FindPackageHandleStandardArgs)

# handle the QUIETLY and REQUIRED arguments and set EXODUS_FOUND to TRUE if 
# all listed variables are TRUE
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Exodus DEFAULT_MSG EXODUS_LIBRARIES EXODUS_INCLUDE_DIR)

MARK_AS_ADVANCED(EXODUS_INCLUDE_DIR EXODUS_LIBRARIES)
