name: C++ CMake Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Release, Debug]
        compiler: 
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build g++ clang gfortran

    - name: Install Dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install cmake ninja gcc  # GCC includes gfortran

    - name: Configure CMake
      run: |
        cmake -B build \
              -DCMAKE_C_COMPILER=${{ matrix.compiler.cc }} \
              -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -G Ninja

    - name: Build Project
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Run Tests
      working-directory: build
      run: ctest --output-on-failure
