name: CMake build tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: 
      image: docker.io/kzoli39/custom-ubuntu-firefly:latest
      volumes: 
        - ${{ github.workspace }}:/firefly

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        cpp_compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v4

    - name: Initialize Git Submodules
      run: git submodule update --init --recursive

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y doxygen

    - name: Configure CMake
      run: >
        cmake -B /firefly/build
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S /firefly

    - name: Build
      run: cmake --build /firefly/build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: /firefly/build
      run: |
        ctest --build-config ${{ matrix.build_type }} --output-on-failure
