name: Generate Doxygen Docs

on:
  push:
    branches:
      - obay
  pull_request:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Run Doxygen
        run: doxygen Doxyfile

      - name: Check if docs directory exists
        run: |
          if [ ! -d "docs" ]; then
            echo "❌ The docs directory was not created!"
            exit 1
          fi

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
